
CREATE TABLE temp_acc(GOLD_ID VARCHAR(15) NOT NULL, PROJECT_NAME TEXT, NCBI_BIOPROJECT_ACCESSION VARCHAR(30), NCBI_BIOSAMPLE_ACCESSION VARCHAR(30), ANALYSIS_PROJECT VARCHAR(30), GENBANK_ID VARCHAR(30), IMG_TAXON_ID INTEGER, ORGANISM_NAME TEXT, NCBI_TAXONOMY_ID INTEGER, TEMPERATURE_EXACT VARCHAR(10), TEMPERATURE_OPTIMUM VARCHAR(10), TEMPERATURE_RANGE TEXT, ASSEMBLY_ACCESSION TEXT, FPT_PATH TEXT, TEMPERATURE_OPTIMUM_CLEAN REAL);
.mode csv
.import './temp_acc_data_publish.csv' temp_acc
CREATE TABLE GOLD_FEATURES(GOLD_ID VARCHAR(15) NOT NULL, OGT REAL NOT NULL, rRNA_16S_GC REAL, rRNA_5S_GC REAL, tRNA_GC REAL, F_IVYWREL REAL, HELICES_POS_CHARGED REAL, HELICES_NEG_CHARGED REAL, HELICES_POLAR REAL, HELICES_HYDROPHOBIC REAL, HELICES_G REAL, HELICES_P REAL, BETA_POS_CHARGED REAL, BETA_NEG_CHARGED REAL, BETA_POLAR REAL, BETA_HYDROPHOBIC REAL, BETA_G REAL, BETA_P REAL, LOOPS_POS_CHARGED REAL, LOOPS_NEG_CHARGED REAL, LOOPS_POLAR REAL, LOOPS_HYDROPHOBIC REAL, LOOPS_G REAL, LOOPS_P REAL, SURFACE_ACC_POS_CHARGED REAL, SURFACE_ACC_NEG_CHARGED REAL, SURFACE_ACC_POLAR REAL, SURFACE_ACC_HYDROPHOBIC REAL);
CREATE TABLE GOLD_PROTEINS (GOLD_ID VARCHAR (15) NOT NULL, PROTEIN_ACC VARCHAR (20) NOT NULL, UNQ_ID VARCHAR (50), PRIMARY KEY (GOLD_ID, PROTEIN_ACC));
CREATE TABLE BEST_MODELS (UNQ_ID VARCHAR (50), BEST_MODEL VARCHAR (50), DOPE_SCORE REAL);
CREATE TABLE AA_LOOPS (BEST_MODEL VARCHAR (50) PRIMARY KEY, POS_CHARGED REAL, NEG_CHARGED REAL, POLAR REAL, HYDROPHOBIC REAL, P REAL, G REAL);
CREATE TABLE AA_BETA (BEST_MODEL VARCHAR (50) PRIMARY KEY, POS_CHARGED REAL, NEG_CHARGED REAL, POLAR REAL, HYDROPHOBIC REAL, P REAL, G REAL);
CREATE TABLE AA_HELICES (BEST_MODEL VARCHAR (50) PRIMARY KEY, POS_CHARGED REAL, NEG_CHARGED REAL, POLAR REAL, HYDROPHOBIC REAL, P REAL, G REAL);
CREATE TABLE AA_SURFACE_ACC (BEST_MODEL VARCHAR (50) PRIMARY KEY, POS_CHARGED REAL, NEG_CHARGED REAL, POLAR REAL, HYDROPHOBIC REAL);
INSERT INTO GOLD_FEATURES (GOLD_ID, OGT) SELECT DISTINCT(GOLD_ID), TEMPERATURE_OPTIMUM_CLEAN FROM temp_acc WHERE TEMPERATURE_OPTIMUM_CLEAN!=''; 
