#!/bin/bash

DB=${1}
sqlite3 ${DB} "INSERT INTO AA_HELICES (BEST_MODEL) SELECT BEST_MODEL FROM BEST_MODELS;"
sqlite3 ${DB} "INSERT INTO AA_BETA (BEST_MODEL) SELECT BEST_MODEL FROM BEST_MODELS;"
sqlite3 ${DB} "INSERT INTO AA_LOOPS (BEST_MODEL) SELECT BEST_MODEL FROM BEST_MODELS;"
sqlite3 ${DB} "INSERT INTO AA_SURFACE_ACC (BEST_MODEL) SELECT BEST_MODEL FROM BEST_MODELS;"